#!/usr/bin/env python3
"""
Generate local TradingAgents-CN runtime config from environment variables.

This script is public-safe:
- it does not depend on ~/.codex
- it does not embed secrets in the repository
- it only writes local runtime files under the current checkout
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
ROOT_ENV_LOCAL = REPO_ROOT / ".env.local"
ROOT_ENV = REPO_ROOT / ".env"
FRONTEND_ENV_LOCAL = REPO_ROOT / "frontend" / ".env.local"
MODELS_JSON = REPO_ROOT / "config" / "models.json"
SETTINGS_JSON = REPO_ROOT / "config" / "settings.json"

PROVIDER_KEY_ENV_MAP = {
    "openai": "OPENAI_API_KEY",
    "deepseek": "DEEPSEEK_API_KEY",
    "dashscope": "DASHSCOPE_API_KEY",
    "google": "GOOGLE_API_KEY",
    "anthropic": "ANTHROPIC_API_KEY",
    "openrouter": "OPENROUTER_API_KEY",
    "qianfan": "QIANFAN_API_KEY",
    "zhipu": "ZHIPU_API_KEY",
    "moonshot": "MOONSHOT_API_KEY",
}


def _load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


def _parse_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _required_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise SystemExit(f"Missing required environment variable: {name}")
    return value


def _optional_env(name: str, default: str = "") -> str:
    return os.getenv(name, default).strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Bootstrap local runtime config from env variables")
    parser.add_argument("--env-file", help="Optional env file to load before generating config")
    args = parser.parse_args()

    if args.env_file:
        _load_env_file(Path(args.env_file).expanduser().resolve())

    provider_name = _required_env("TA_MODEL_PROVIDER").lower()
    model_name = _required_env("TA_MODEL_NAME")
    base_url = _required_env("TA_MODEL_BASE_URL")
    api_key = _required_env("TA_MODEL_API_KEY")
    provider_display_name = _optional_env("TA_PROVIDER_DISPLAY_NAME", f"{provider_name} local")
    data_source = _optional_env("TA_DEFAULT_DATA_SOURCE", "AKShare")
    backend_port = _optional_env("TA_BACKEND_PORT", "8000")
    frontend_port = _optional_env("TA_FRONTEND_PORT", "3000")
    minimal_startup = _optional_env("TA_ENABLE_MINIMAL_STARTUP", "true").lower() in {
        "1",
        "true",
        "yes",
        "on",
    }

    existing_env = _parse_env(ROOT_ENV_LOCAL)
    jwt_secret = existing_env.get("JWT_SECRET") or secrets.token_urlsafe(32)
    csrf_secret = existing_env.get("CSRF_SECRET") or secrets.token_urlsafe(32)

    provider_api_env = PROVIDER_KEY_ENV_MAP.get(provider_name, f"{provider_name.upper()}_API_KEY")

    root_env_lines = [
        "# Generated by scripts/startup/bootstrap_local_env.py",
        "# Local-only runtime config. Do not commit generated files with secrets.",
        "DEBUG=true",
        "HOST=0.0.0.0",
        f"PORT={backend_port}",
        f"ALLOWED_ORIGINS=[\"http://localhost:{frontend_port}\"]",
        "ALLOWED_HOSTS=[\"*\"]",
        "",
        "# Databases",
        "MONGODB_ENABLED=true",
        f"MONGODB_HOST={_optional_env('MONGODB_HOST', 'localhost')}",
        f"MONGODB_PORT={_optional_env('MONGODB_PORT', '27017')}",
        f"MONGODB_USERNAME={_optional_env('MONGODB_USERNAME')}",
        f"MONGODB_PASSWORD={_optional_env('MONGODB_PASSWORD')}",
        f"MONGODB_DATABASE={_optional_env('MONGODB_DATABASE', 'tradingagents')}",
        f"MONGODB_AUTH_SOURCE={_optional_env('MONGODB_AUTH_SOURCE', 'admin')}",
        "",
        "REDIS_ENABLED=true",
        f"REDIS_HOST={_optional_env('REDIS_HOST', 'localhost')}",
        f"REDIS_PORT={_optional_env('REDIS_PORT', '6379')}",
        f"REDIS_PASSWORD={_optional_env('REDIS_PASSWORD')}",
        f"REDIS_DB={_optional_env('REDIS_DB', '0')}",
        "",
        "# Security",
        f"JWT_SECRET={jwt_secret}",
        "JWT_ALGORITHM=HS256",
        "ACCESS_TOKEN_EXPIRE_MINUTES=60",
        "REFRESH_TOKEN_EXPIRE_DAYS=30",
        f"CSRF_SECRET={csrf_secret}",
        "",
        "# Model runtime",
        f"{provider_api_env}={api_key}",
        f"TRADINGAGENTS_DEFAULT_MODEL={model_name}",
        f"TRADINGAGENTS_QUICK_MODEL={model_name}",
        f"TRADINGAGENTS_DEEP_MODEL={model_name}",
        f"TRADINGAGENTS_MINIMAL_STARTUP={'true' if minimal_startup else 'false'}",
        "USE_MONGODB_STORAGE=true",
        "TA_USE_APP_CACHE=true",
        "TRADINGAGENTS_LOG_LEVEL=INFO",
        "TRADINGAGENTS_RESULTS_DIR=./results",
        "TRADINGAGENTS_DATA_DIR=./data",
        "TRADINGAGENTS_CACHE_DIR=./cache",
        "NO_PROXY=localhost,127.0.0.1",
    ]

    if provider_name == "openai":
        root_env_lines.extend(
            [
                f"OPENAI_API_KEY={api_key}",
                f"OPENAI_BASE_URL={base_url}",
            ]
        )

    root_env_content = "\n".join(root_env_lines) + "\n"

    frontend_env_lines = [
        "# Generated by scripts/startup/bootstrap_local_env.py",
        f"VITE_API_BASE_URL=http://localhost:{backend_port}",
        f"VITE_WS_URL=ws://localhost:{backend_port}",
        "VITE_APP_TITLE=TradingAgents-CN Local",
        "VITE_APP_ENV=development",
    ]
    frontend_env_content = "\n".join(frontend_env_lines) + "\n"

    models_payload = [
        {
            "provider": provider_name,
            "model_name": model_name,
            "api_key": "",
            "base_url": base_url,
            "max_tokens": 4000,
            "temperature": 0.7,
            "enabled": True,
        }
    ]
    settings_payload = {
        "default_model": model_name,
        "quick_analysis_model": model_name,
        "deep_analysis_model": model_name,
        "quick_think_llm": model_name,
        "deep_think_llm": model_name,
        "default_provider": provider_name,
        "default_data_source": data_source,
        "log_level": "INFO",
        "enable_monitoring": True,
    }

    _write_text(ROOT_ENV_LOCAL, root_env_content)
    _write_text(ROOT_ENV, root_env_content)
    _write_text(FRONTEND_ENV_LOCAL, frontend_env_content)
    _write_text(MODELS_JSON, json.dumps(models_payload, indent=2, ensure_ascii=False) + "\n")
    _write_text(SETTINGS_JSON, json.dumps(settings_payload, indent=2, ensure_ascii=False) + "\n")

    print("Generated local runtime files:")
    print(f"  - {ROOT_ENV_LOCAL}")
    print(f"  - {ROOT_ENV}")
    print(f"  - {FRONTEND_ENV_LOCAL}")
    print(f"  - {MODELS_JSON}")
    print(f"  - {SETTINGS_JSON}")
    print("Model profile:")
    print(f"  - provider: {provider_name}")
    print(f"  - provider_display_name: {provider_display_name}")
    print(f"  - model: {model_name}")
    print(f"  - base_url: {base_url}")
    print(f"  - api key env: {provider_api_env}")


if __name__ == "__main__":
    main()
