from typing import Annotated, Any, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState

# 导入统一日志系统
from tradingagents.utils.logging_init import get_logger
logger = get_logger("default")


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    analysis_id: Annotated[str, "Analysis/task identifier used for PR-002 traceability"]
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # 🔧 死循环修复: 工具调用计数器
    market_tool_call_count: Annotated[int, "Market analyst tool call counter"]
    news_tool_call_count: Annotated[int, "News analyst tool call counter"]
    sentiment_tool_call_count: Annotated[int, "Social media analyst tool call counter"]
    fundamentals_tool_call_count: Annotated[int, "Fundamentals analyst tool call counter"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    # AlphaGuard PR-002 authoritative machine decision fields. The legacy text
    # fields remain display/report-only and must never overwrite these objects.
    normal_trade_plan: Annotated[
        Optional[dict[str, Any]], "Validated AlphaGuard NormalTradePlan"
    ]
    top_review_decision: Annotated[
        Optional[dict[str, Any]], "Validated AlphaGuard TopReviewDecision"
    ]
    decision_error: Annotated[
        Optional[dict[str, Any]], "Explicit structured-decision failure details"
    ]
    normal_model_meta: Annotated[
        Optional[dict[str, Any]], "Normal model execution audit metadata"
    ]
    top_model_meta: Annotated[
        Optional[dict[str, Any]], "Top review model execution audit metadata"
    ]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
